### ISSUE TITLE
Error retrieving kptncook access token

### ISSUE THREAD

**Issue by brotkrume** [ephes/kptncook#25] opened 2023-10-11 20:07 UTC
Hi,

first, great work :)

But I'm not able to get the access token. "404 not found" :(

Using Win 11 with Windows Terminal, Python 3.12.

Any idea, what I'm doing wrong? 

Many thanks & Regards,
Matthias

Traceback (most recent call last) 
│ xxx\kptncook\Lib\site-packages\kptncook\__init__.py:179 in          │
│ get_kptncook_access_token                                                                        │
│                                                                                                  │
│   176 │   username = Prompt.ask("Enter your kptncook email address")                             │
│   177 │   password = Prompt.ask("Enter your kptncook password", password=True)                   │
│   178 │   client = KptnCookClient()                                                              │
│ ❱ 179 │   access_token = client.get_access_token(username, password)                             │
│   180 │   rprint("your access token: ", access_token)                                            │
│   181                                                                                            │
│   182                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │   client = <kptncook.api.KptnCookClient object at 0x000001C1D640DDC0> │                        │
│ │ password = 'xxx'                                     │                        │
│ │ username = 'xxx@xxx.xx'                              │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ xxx\kptncook\Lib\site-packages\kptncook\api.py:87 in                │
│ get_access_token                                                                                 │
│                                                                                                  │
│    84 │   │   │   "/login/userpass",                                                             │
│    85 │   │   │   json={"email": username, "password": password},                                │
│    86 │   │   )                                                                                  │
│ ❱  87 │   │   response.raise_for_status()                                                        │
│    88 │   │   token_data = response.json()                                                       │
│    89 │   │   return token_data["accessToken"]                                                   │
│    90                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │ password = 'xxx'                                     │                        │
│ │ response = <Response [404 Not Found]>                                 │                        │
│ │     self = <kptncook.api.KptnCookClient object at 0x000001C1D640DDC0> │                        │
│ │ username = 'xxx@xxx.xx'                              │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ xxx\kptncook\Lib\site-packages\httpx\_models.py:749 in              │
│ raise_for_status                                                                                 │
│                                                                                                  │
│    746 │   │   }                                                                                 │
│    747 │   │   error_type = error_types.get(status_class, "Invalid status code")                 │
│    748 │   │   message = message.format(self, error_type=error_type)                             │
│ ❱  749 │   │   raise HTTPStatusError(message, request=request, response=self)                    │
│    750 │                                                                                         │
│    751 │   def json(self, **kwargs: typing.Any) -> typing.Any:                                   │
│    752 │   │   if self.charset_encoding is None and self.content and len(self.content) > 3:      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   error_type = 'Client error'                                                                │ │
│ │  error_types = {                                                                             │ │
│ │                │   1: 'Informational response',                                              │ │
│ │                │   3: 'Redirect response',                                                   │ │
│ │                │   4: 'Client error',                                                        │ │
│ │                │   5: 'Server error'                                                         │ │
│ │                }                                                                             │ │
│ │      message = "Client error '404 Not Found' for url                                         │ │
│ │                'https://mobile.kptncook.com//login/userpas"+91                               │ │
│ │      request = <Request('POST', 'https://mobile.kptncook.com//login/userpass')>              │ │
│ │         self = <Response [404 Not Found]>                                                    │ │
│ │ status_class = 4                                                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HTTPStatusError: Client error '404 Not Found' for url 'https://mobile.kptncook.com//login/userpass'

**Comment by marcoacheron** [comment] 2023-10-13 22:22
I ran into the same issue and had to edit some files. Specifically, there is an extra / added to the URLs. Also, if you are trying to access the English version of the recipes, you have to replace "de" with "en". Below are my fixes, but I'm sure there is a global way to prevent this from happening in the future.

Edit ../site-packages/kptncook/api.py. 
   Line 71: remove the / in front of recipes
   Line 84: remove the / in front of login
   Line 95: remove the / in front of favorites
   Line 104: remove the / in front of recipes

This should allow the commands to work. It isn't pretty, but I hope this helps.

**Comment by ephes** [comment] 2023-10-14 12:31
> Hi,
> 
> first, great work :)

Thanks :) 

> But I'm not able to get the access token. "404 not found" :(

Yup, I can reproduce your issue. The URLs are just broken :(.

**Comment by ephes** [comment] 2023-10-14 12:38
> I ran into the same issue and had to edit some files. Specifically, there is an extra / added to the URLs. Also, if you are trying to access the English version of the recipes, you have to replace "de" with "en". Below are my fixes, but I'm sure there is a global way to prevent this from happening in the future.

Ok, I'm not sure how to handle this de vs en thing, maybe a configuration option?

> Edit ../site-packages/kptncook/api.py. Line 71: remove the / in front of recipes | also change the "de" to "en" if you require the English version Line 84: remove the / in front of login Line 95: remove the / in front of favorites Line 104: remove the / in front of recipes
> 
> This should allow some of the commands to work. It isn't pretty, but I hope this helps.

Yes, I can confirm this fixes the broken URLs. It also works for the login url from the original poster. Do you want to try to fix it and create a PR? I can provide some help and guide you through the process if you like to 😃.

The root cause is in the to_url-Method of KptnCookClient. I would start by writing a test for this method, which breaks when there's a "//" in the returned URL. And then use urljoin from urllib.parse to combine the base url with the path instead of the f-string. This should fix it.

**Comment by brotkrume** [comment] 2023-10-14 12:40
Many thanks for your help.

**Comment by ephes** [comment] 2023-10-19 07:29
> Many thanks for your help.

Do you want to give it a try? Otherwise I'll do it over the weekend..

**Comment by brotkrume** [comment] 2023-10-19 07:36
Sorry, 'till end of month I have no time for this :(

**Comment by ephes** [comment] 2023-10-21 14:09
Ok, fixed in [0.0.12](https://github.com/ephes/kptncook/releases/tag/0.0.12) 😅.

**Closed by ephes** 2023-10-21 14:09 UTC
